//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam2
    {
        public short examID { get; set; }
        public string subject { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.DateTime> examDate { get; set; }
        public Nullable<int> duration { get; set; }
        public string classroom { get; set; }
        public string faculty { get; set; }
        public string status { get; set; }
    }
}
